### ISSUE TITLE
All of this Boomi stuff can be ported over to Mule

### ISSUE THREAD

**Issue by granthbr** [granthbr/innotas-groovy#1]
Convert to Mule java/groovy classes for reusability project

**Comment by granthbr** [comment]
Started design work to covert to Mule. Adding this as a git module to integration collab project.

**Comment by granthbr** [comment]
No need to keep this issue open. Created as an enhancement but will exist in a different repo

**Comment by anloehr** [comment]
I think that's a great idea!

On Mon, Jun 22, 2015 at 11:30 AM, Brandon Grantham <notifications@github.com

**Comment by anloehr** [comment]
Thanks for letting me know.

On Mon, Jun 22, 2015 at 11:36 AM, Brandon Grantham <notifications@github.com
